language: scala

scala:
  - 2.12.10

stages:
  - name: styling
  - name: test

jobs:
  include:
    - stage: test
      install: pip install --user codecov
      script: sbt coverage test multi-jvm:test coverageReport && codecov

    - stage: styling
      script: sbt scalafmtCheck test:scalafmtCheck multi-jvm:scalafmtCheck

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier
